### ISSUE TITLE
Doesn't work with erb'd yaml file even though it's a typical setup

### ISSUE THREAD

**Issue by JakeTheSnake3p0** [jalkoby/squasher#24]
Since I don't want to store my username and password in the [database.yml](http://edgeguides.rubyonrails.org/configuring.html#configuring-a-database) file (notice the part about ERB tags), this is my configuration:

**config/database.yml**
```yaml
mysql: &MYSQL
  adapter: mysql2
  port: 3306
default: &DEFAULT
  host: localhost
  username: <%= Rails.application.secrets.database_username %>
  password: <%= Rails.application.secrets.database_password %>
  encoding: utf8
  collation: utf8_unicode_ci
  timeout: 5000
  reconnect: true
  pool: 5
development:
  <<: *MYSQL
  <<: *DEFAULT
  database: manager_development
test:
  adapter: sqlite3
  <<: *DEFAULT
  database: ':memory:'
  verbosity: silent
staging:
  <<: *MYSQL
  <<: *DEFAULT
  database: manager_development
production:
  <<: *MYSQL
  <<: *DEFAULT
  database: manager_production
```

It would be a trivial temporary fix to copy/paste the actual values in my secrets.yml file just to run this command but is it really necessary? For that matter, why are username/passwords necessary? It isn't actually modifying my databases.

Reported Error: `Squasher couldn't load database.yml. Please, make sure that it's present and doesn't include any ruby code.`
