### ISSUE TITLE
Error while cleaning old migrations in database

### ISSUE THREAD

**Issue by JakeTheSnake3p0** [jalkoby/squasher#25]
I receive this error when clearing out old migration data from the database:

``` ruby
Squasher is applying the clean migration
rake aborted!
NoMethodError: undefined method `each' for #<String:0xbdea37c>
/home/vagrant/.rvm/gems/ruby-2.2.1@pos/gems/activerecord-4.2.6/lib/active_record/connection_adapters/connection_specification.rb:150:in `resolve_all'
/home/vagrant/.rvm/gems/ruby-2.2.1@pos/gems/activerecord-4.2.6/lib/active_record/connection_handling.rb:69:in `resolve'
/home/vagrant/.rvm/gems/ruby-2.2.1@pos/gems/activerecord-4.2.6/lib/active_record/core.rb:46:in `configurations='
/home/vagrant/.rvm/gems/ruby-2.2.1@pos/gems/activerecord-4.2.6/lib/active_record/railtie.rb:117:in `block (2 levels) in <class:Railtie>'
/home/vagrant/.rvm/gems/ruby-2.2.1@pos/gems/activesupport-4.2.6/lib/active_support/lazy_load_hooks.rb:38:in `instance_eval'
/home/vagrant/.rvm/gems/ruby-2.2.1@pos/gems/activesupport-4.2.6/lib/active_support/lazy_load_hooks.rb:38:in `execute_hook'
/home/vagrant/.rvm/gems/ruby-2.2.1@pos/gems/activesupport-4.2.6/lib/active_support/lazy_load_hooks.rb:28:in `block in on_load'
/home/vagrant/.rvm/gems/ruby-2.2.1@pos/gems/activesupport-4.2.6/lib/active_support/lazy_load_hooks.rb:27:in `each'
/home/vagrant/.rvm/gems/ruby-2.2.1@pos/gems/activesupport-4.2.6/lib/active_support/lazy_load_hooks.rb:27:in `on_load'
/home/vagrant/.rvm/gems/ruby-2.2.1@pos/gems/activerecord-4.2.6/lib/active_record/railtie.rb:116:in `block in <class:Railtie>'
/home/vagrant/.rvm/gems/ruby-2.2.1@pos/gems/railties-4.2.6/lib/rails/initializable.rb:30:in `instance_exec'
/home/vagrant/.rvm/gems/ruby-2.2.1@pos/gems/railties-4.2.6/lib/rails/initializable.rb:30:in `run'
/home/vagrant/.rvm/gems/ruby-2.2.1@pos/gems/railties-4.2.6/lib/rails/initializable.rb:55:in `block in run_initializers'
/home/vagrant/.rvm/gems/ruby-2.2.1@pos/gems/railties-4.2.6/lib/rails/initializable.rb:54:in `run_initializers'
/home/vagrant/.rvm/gems/ruby-2.2.1@pos/gems/railties-4.2.6/lib/rails/application.rb:352:in `initialize!'
/home/vagrant/rails/dev.pos/config/environment.rb:5:in `<top (required)>'
/home/vagrant/.rvm/gems/ruby-2.2.1@pos/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
/home/vagrant/.rvm/gems/ruby-2.2.1@pos/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `block in require'
/home/vagrant/.rvm/gems/ruby-2.2.1@pos/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240:in `load_dependency'
/home/vagrant/.rvm/gems/ruby-2.2.1@pos/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
/home/vagrant/.rvm/gems/ruby-2.2.1@pos/gems/railties-4.2.6/lib/rails/application.rb:328:in `require_environment!'
/home/vagrant/.rvm/gems/ruby-2.2.1@pos/gems/railties-4.2.6/lib/rails/application.rb:457:in `block in run_tasks_blocks'
/home/vagrant/.rvm/gems/ruby-2.2.1@pos/bin/ruby_executable_hooks:15:in `eval'
/home/vagrant/.rvm/gems/ruby-2.2.1@pos/bin/ruby_executable_hooks:15:in `<main>'
```

At this point in time:
- The old migration files have been deleted
- schema.rb has been reset to an older version (doesn't make sense unless this error occurred during a migration process and never finished migrating up to the latest migration. My app's schema.rb should always be up to date with the latest migration regardless of what this gem does)
- init_schema.rb has been created with the same timestamp as schema.rb
- squasher_clean.rb has been created (contents below)

``` ruby
class SquasherClean < ActiveRecord::Migration
  class SchemaMigration < ActiveRecord::Base
  end

  def up
    migrations = Dir.glob(File.join(File.dirname(__FILE__), '*.rb'))
    versions = migrations.map { |file| File.basename(file)[/\A\d+/] }
    SchemaMigration.where("version NOT IN (?)", versions).delete_all
  end

  def down
  end
end
```

**Comment by jalkoby** [comment]
Hello and sorry for long response(I've been out the Internet recent day). In the couple next days I'm going to handle the issues. Thank you for the feedback

**Comment by jalkoby** [comment]
I've got the time to fix this. At this point to figure out the solution, I need the content of database.yml. Could you provide it?

**Comment by JakeTheSnake3p0** [comment]
```yaml
mysql: &MYSQL
  adapter: mysql2
  port: 3306
default: &DEFAULT
  host: localhost
  username: my_username
  password: my_password
  encoding: utf8
  collation: utf8_unicode_ci
  timeout: 5000
  reconnect: true
  pool: 5
development:
  <<: *MYSQL
  <<: *DEFAULT
  database: pos_development
test:
  <<: *DEFAULT
  adapter: sqlite3
  database: ':memory:'
  verbosity: silent
staging:
  <<: *MYSQL
  <<: *DEFAULT
  database: pos_staging
production:
  <<: *MYSQL
  <<: *DEFAULT
  database: pos_production
```
