### ISSUE TITLE
database.yml is left somehow misconfigured when an error occurs

### ISSUE THREAD

**Issue by JakeTheSnake3p0** [jalkoby/squasher#26]
When an error such as #25 occurs, re-running the `squasher` command yields 

> Squasher couldn't load `database.yml`. Please, make sure that it's present and doesn't include any ruby code.

 - even though the file looks like it did when the command was run the 1st time with no apparent problems.

I have to simply hit Ctrl+S (re-save) the database.yml file as-is and then rerunning `squasher` no longer yields this error. Somewhere along the line during the `squasher` command, I see the file change in my text editor - so squasher is doing something to it directly and not reverting the changes back immediately and perfectly.

database.yml:

```yaml
mysql: &MYSQL
  adapter: mysql2
  port: 3306
default: &DEFAULT
  host: localhost
  encoding: utf8
  collation: utf8_unicode_ci
  timeout: 5000
  reconnect: true
  pool: 5
  username: root
  password: vagrant
development:
  <<: *MYSQL
  <<: *DEFAULT
  database: pos_development
test:
  <<: *DEFAULT
  adapter: sqlite3
  database: ':memory:'
  verbosity: silent
staging:
  <<: *MYSQL
  <<: *DEFAULT
  database: pos_staging
production:
  <<: *MYSQL
  <<: *DEFAULT
  database: pos_production
```
