### ISSUE TITLE
ActiveRecord::NoDatabaseError: FATAL:  database "squasher" does not exist

### ISSUE THREAD

**Issue by aaronpod** [jalkoby/squasher#49]
I'm trying to run squasher with a Rails 5.0.1 app with postgres and am getting the following error:

```
ActiveRecord::NoDatabaseError: FATAL:  database "squasher" does not exist
...
PG::ConnectionBad: FATAL:  database "squasher" does not exist
...
Tasks: TOP => db:drop => db:check_protected_environments => environment
```

The development section of my database.yml file looks like:

```
development:
  adapter: postgresql
  encoding: unicode
  database: db/app_development
  host: localhost
  pool: 5
  username:
  password:
```

Any ideas? Thanks!
