### ISSUE TITLE
PG::ConnectionBad: FATAL:  database "squasher" does not exist

### ISSUE THREAD

**Issue by drselump14** [jalkoby/squasher#61]
Got this error, when invoking `bundle exec squasher 2020/6 -m 5.0`
```
Caused by:
PG::ConnectionBad: FATAL:  database "squasher" does not exist
```

my `config/database.yml` is

```
default: &default
  adapter: postgresql
  encoding: unicode
  timeout: 5000


development:
  <<: *default
  database: foobar

```

Any help would be appreciated 🙏
