### ISSUE TITLE
Squasher couldn't load `database.yml`. Please, make sure that it's present and doesn't include any ruby code.

### ISSUE THREAD

**Issue by YutoYasunaga** [jalkoby/squasher#70]
Hello, this issue happen recently.
When I run squasher, this error occurred:

`Squasher couldn't load `database.yml`. Please, make sure that it's present and doesn't include any ruby code.`

And this is my config/database.yml file:

```
default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: docker
  host: '127.0.0.1'

development:
  <<: *default
  database: tiengnhatit_development

test:
  <<: *default
  database: tiengnhatit_test

```

**Comment by lxxxvi** [comment]
I think this is related to Ruby 3.1 which upgrades to Psych 4.0.

> * Psych 4.0 changes `Psych.load` to use `safe_load` by default. You may need to use Psych 3.3.2 for migrating to this behavior. [Bug #17866]

(Source: https://www.ruby-lang.org/en/news/2021/12/25/ruby-3-1-0-released/)

The corresponding PR can be found here:

* https://github.com/ruby/psych/pull/487

---

`.safe_load` uses `aliases: false` meaning that if you have something like this

```yaml
default: &default

test:
  <<: *default
```

the load won't work anymore. One solution would be to use `YAML.unsafe_load` here

https://github.com/jalkoby/squasher/blob/714ac99d549adc05b31af664ad5354ccaeb6393f/lib/squasher/config.rb#L13

or even just `YAML.load_file(path)`?
